# Generated by Django 3.2.23 on 2024-02-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20240127_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexaminationscore',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.examination'),
        ),
    ]
