# Generated by Django 3.2.23 on 2024-02-17 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_setting', '0001_initial'),
        ('school_app', '0004_alter_studentexaminationscore_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_class',
        ),
        migrations.CreateModel(
            name='StudentCurrentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_setting.classroom')),
                ('students', models.ManyToManyField(related_name='student_current_class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
